### ISSUE TITLE
Enable POP3 on 995 or 110 port for GMAIL.

### ISSUE THREAD

**Issue by erajuan** [runeasymail/easymail#106]
enable pop3 on por 995 or 110 for import mails from GMAIL, because GMAIl does not import from IMAP

**Comment by pavel-tashev** [comment]
Thank you for the task Erajuan. We will review the it.

**Comment by GyunerZeki** [comment]
It should be enabled. Can you provide a bit more details how do you install EasyMail?

**Comment by erajuan** [comment]
Download ans start the script install.sh , without docker
```
> wget https://github.com/runeasymail/easymail/archive/v0.6.3.tar.gz -O easymail.tgz && mkdir easymail && cd easymail && tar -xvzf ../easymail.tgz --strip 1 
> bash install.sh
```
I remove RAM + SWAP valitation (for DROPLET on digital ocean 1GB RAM)
Ubuntu 10.04.2 x 64

**Comment by erajuan** [comment]
**Configuration with server POP 110**
El servidor ha denegado el acceso POP3 a este nombre de usuario y contraseña.
El servidor ha devuelto el error "[AUTH] Plaintext authentication disallowed on non-secure (SSL/TLS) connections."
**Configuration with server POP 995**
Se ha producido un problema al conectar con mail.example.com
El servidor ha devuelto el error "Connection refused"

The user and password is ok, I login in Roundcube

**Comment by GyunerZeki** [comment]
Hi 

It seems like you are using mail.example.com which is not a valid name. Did you try with your own domain?

Thanks,
Gyuner Zeki

**Comment by erajuan** [comment]
Yes. I use my domain

**Comment by GyunerZeki** [comment]
Hi @erajuan 

What do you have as a result if you try to check the port for example with http://ping.eu/port-chk/ ?

Thanks,
Gyuner

**Comment by erajuan** [comment]
Port 110 is OPEN
Port 995 is CLOSED

COPY from last comment
Configuration with server POP 110
El servidor ha denegado el acceso POP3 a este nombre de usuario y contraseña.
El servidor ha devuelto el error "[AUTH] Plaintext authentication disallowed on non-secure (SSL/TLS) connections."

**Comment by GyunerZeki** [comment]
Can you send me screenshot from the Gmail page where you put the settings?

**Comment by erajuan** [comment]
![mail-configurations](https://cloud.githubusercontent.com/assets/6233118/25208345/f4e474e4-2528-11e7-87fd-53205c1513b5.png)

**Comment by GyunerZeki** [comment]
Hi @erajuan 

I have just tested it on one of live server based on EasyMail and here are the settings.
http://store.picbg.net/pubpic/8F/4C/6127f9b88fe08f4c.png

Can you please check is that works for you?

Thanks,
Gyuner Zeki

**Comment by erajuan** [comment]
Hi @GyunerZeki 
I tried that, but my port 995 is closed (http://ping.eu/port-chk/)
My server based on EasyMail v0.6.3
Port 995
Server returned error: "Connection refused"

**Comment by GyunerZeki** [comment]
Hi @erajuan 

I have just tested in the new version of the EasyMail and it doesn't really work on the last a few versions. From tomorrow we're starting to search for the problem and try to fix it really ASAP.

In the slack channel (runeasymail.slack.com) we are starting a discussion about it and fix it. If you want to be informed of details you can join too.

I personally would like to say thank you for reporting this problem and I will go back to you when we resolve that problem.

Thanks,
Gyuner

**Comment by erajuan** [comment]
Thanks @GyunerZeki

**Comment by GyunerZeki** [comment]
Hi @erajuan 

I found the problem. Since you already have an installed version of Easymail cam you try to execute the following can and check is solving the 995 port problem.

echo "
ssl = required
ssl_cert = </etc/dovecot/dovecot.pem
ssl_key = </etc/dovecot/private/dovecot.pem
" >> /etc/dovecot/dovecot.conf && service dovecot restart

Please let me know the result.

Thanks,
Gyuner

**Comment by GyunerZeki** [comment]
This problem is fixed on https://github.com/runeasymail/easymail/pull/139 and will be released on the new version of Easymail

**Comment by erajuan** [comment]
Yes. The problem was fixed.
Thanks.
