### ISSUE TITLE
Generate self-signed SSL via the ManagmentAPI and make the switching between the SSL options possible

### ISSUE THREAD

**Issue by pavel-tashev** [runeasymail/easymail#131]
During the development of this task bear in mind the following. The users must be able to:
- generate self-signed SSL certificate
- generate Letsencrypt SSL certificate
- add own SSL certificate

and they also have to be able to switch between any of these three options whenever they decide.

**Comment by GyunerZeki** [comment]
It seems no demand for that feature, closing the ticket.
