### ISSUE TITLE
After successful build:

### ISSUE THREAD

**Issue by GyunerZeki** [runeasymail/easymail#138]
- connect to the server and sends an email via SMTP.
- connect to the server and make mail checkw via IMAP and POP3

**Comment by GyunerZeki** [comment]
**POP3**
- STARTTLS on port 110
- SSL on port 995

**IMAP**
- STARTTLS on port 143
- SSL on port 993

**Comment by pavel-tashev** [comment]
https://github.com/runeasymail/easymail/commit/f5b9d9a563d10604bdad05de43ac8d81e1f5e771
