### ISSUE TITLE
Someone walk me through letsencrypt installation

### ISSUE THREAD

**Issue by cruisemaniac** [runeasymail/easymail#148]
The lets encrypt install failed and keeps saying that it wrote the challenge to /var/www/challenges but was not reachable from the http url.

I also noticed that the https redirect exists for port 80. Is there something I am missing here?

**Comment by GyunerZeki** [comment]
Hi @cruisemaniac 

Which version of Easymail are you using?

Thanks,
Gyuner Zeki

**Comment by cruisemaniac** [comment]
@GyunerZeki I'm running with #tags/v0.6

**Comment by pavel-tashev** [comment]
Our plan is to release a new version of EasyMail where this issue is solved. I will get back to you as soon as we do that!

**Comment by GyunerZeki** [comment]
In the version 1 of EasyMail this is already solved, so closing this ticket.
