### ISSUE TITLE
Easymail Website needs to have form to join slack channel.

### ISSUE THREAD

**Issue by cruisemaniac** [runeasymail/easymail#149]
Currently only an alert exists. But there's no form to accept email ID and inform chan owner that someone wants to join.

**Comment by pavel-tashev** [comment]
Thanks for the suggestion. As soon as we release the new version of EasyMail, we will have more time and we will consider the option to add the form on the website.

**Comment by pavel-tashev** [comment]
Hi mate,

I have just reassigned the task to you. May I please ask you to do it and we will review you Pull Request once you are ready.

Thanks!

**Comment by GyunerZeki** [comment]
No action on that suggestion, closing the ticket. Please reopen in case still relevant
