### ISSUE TITLE
Add domain via api fails (mailuser mysql user insert access denied)

### ISSUE THREAD

**Issue by cruisemaniac** [runeasymail/easymail#150]
When trying to add a domain via the managementapi, the insert record operation fails because the mailserver user does not have rights to insert a record into the db.

the json response is as follows:
```
{
  "error_msg": "Error 1142: INSERT command denied to user 'mailuser'@'localhost' for table 'virtual_domains'",
  "result": false
}
```

**Comment by cruisemaniac** [comment]
Did a little bit of digging around and found this:
```
mysql> SHOW GRANTS FOR 'mailuser'@'127.0.0.1';
+----------------------------------------------------------+
| Grants for mailuser@127.0.0.1                            |
+----------------------------------------------------------+
| GRANT USAGE ON *.* TO 'mailuser'@'127.0.0.1'             |
| GRANT SELECT ON `mailserver`.* TO 'mailuser'@'127.0.0.1' |
+----------------------------------------------------------+
2 rows in set (0.00 sec)
```

This is perhaps playing with the add domain API command?

**Comment by pavel-tashev** [comment]
I will check that!

**Comment by pavel-tashev** [comment]
Hi again,

The issue is fixed and merge to the master branch - commit https://github.com/runeasymail/easymail/commit/416345e7d3fa1ea364eb6112ebcdd42c2825c14e. 

It will be populated to the new version of EasyMail which will be release soon.

Let me know if there is anything I can help with.
