### ISSUE TITLE
Documentation needs improvement

### ISSUE THREAD

**Issue by cruisemaniac** [runeasymail/easymail#151]
* I'm following the documentation to install easymail. After all the steps are completed, I notice that the default sending address is: admin@mail.example.com instead of admin@example.com.

* Putting the system through its tests, a sample email to mail-tester.com reports a score of 0/10. It says that the DKIM keys are invalid.

**Comment by cruisemaniac** [comment]
The DNS records that need to be applied warrant a special page in themselves. There's too much ambiguity between what the system generates vs what the user expects to see...

For ex: Does `mail._domainkey` need to be applied to root domain or `mail` subdomain?
The input that the code accepts for $HOSTNAME is shown to be `mail.example.com` which makes this `mail._domainkey.mail` in most cases (atleast in my case with linode).

We need atleast a few examples that will show the setup in the right direction. I tried to set it up for one of my domains and backed out because there was too much trouble following instructions.

I would like to give this a more patient shot with a spare domain I have lying around if thats okay by you guys.

**Comment by pavel-tashev** [comment]
We will release a new version very soon which and we will have to change the documentation on the website because there will be many changes. We will take into account your notes.

About the DKIM. With the new version, we will provide a new solution for the DKIM because its configuration will be moved to the ManagementAPI.

Your note:

> For ex: Does mail._domainkey need to be applied to root domain or mail subdomain?
> The input that the code accepts for $HOSTNAME is shown to be mail.example.com which makes this mail._domainkey.mail in most cases (atleast in my case with linode).
> 
> We need atleast a few examples that will show the setup in the right direction. I tried to set it up for one of my domains and backed out because there was too much trouble following instructions.
> 
> I would like to give this a more patient shot with a spare domain I have lying around if thats okay by you guys.

will be added to the new document. Thanks!

**Comment by GyunerZeki** [comment]
All of this problems and suggestion are already applied, closing this one, no more action needed. Please re-open in case still need improvement
