### ISSUE TITLE
Why was letsencrypt removed post 0.6.3?

### ISSUE THREAD

**Issue by cruisemaniac** [runeasymail/easymail#152]
Is there an alternative to setting up ssl for domains now that master no longer has letsencrypt?

Also, what was the reason?

**Comment by pavel-tashev** [comment]
The Let's Encrypt certificate was moved to the ManagementAPI. This means that during the installation of EasyMail you will be no longer asked to choose your preferences for SSL certificate. 

You will have to do that after the installation with the help of the ManagementAPI. Read more about it here - https://www.runeasymail.com/master/api#generate-letsencrypt-certificate.

The purpose of this approach is that we want to optimize the installation process and to make it as quick as possible. All other configurations of EasyMail can be done with the ManagementAPI.

In the end of the installation, you will see a message similar to this one:

```
Applications - access:
Roundcube: https://$HOSTNAME/ | username: $ADMIN_EMAIL | password: $PASSWORD
API url: https://$HOSTNAME/api/ | username: $MANAGEMENT_API_USERNAME | password: $MANAGEMENT_API_PASSWORD
```

Use the API URL and the login credentials and execute the corresponding request for generation of Let's Encrypt certificate. Please check the documentation here: https://www.runeasymail.com/master/api#generate-letsencrypt-certificate.

**Comment by pavel-tashev** [comment]
Let me know if you have generated the Let's Encrypt certificate.
