### ISSUE TITLE
Some email providers do not receive email sent from EasyMail

### ISSUE THREAD

**Issue by pavel-tashev** [runeasymail/easymail#158]
There are email providers which do not receive email sent by EasyMail. For example, abv.bg, dir.bg. At the same time, these emails are received by Gmail, Yahoo, etc.

Test and check the DKIM records.

**Comment by GyunerZeki** [comment]
I have just tested it with v1.0.3 with well configured DKIM it works without any problems. Saying that I have sent some emails without DKIM and ABV.BG has just ignored the message. Some provide just ignore message with missing DKIM, but that's not an easymail problem. Closing the ticket. Please re-open in case you still think there is a something to be fixed from Easymail side
