### ISSUE TITLE
error: gpg: keyserver receive failed: public key not found

### ISSUE THREAD

**Issue by erajuan** [runeasymail/easymail#172]
I try install on DROPLET 

- Ubuntu 16.04.3x64 with Docker version 17.06.0-ce
- Ubuntu 14.04.5 x64 with Docker version 17.06.0-ce
- Debian 8.9 with Docker version 17.06.0-ce

In debian the port 25 is used by another program. (docker start ID ) fail

easymail should contain gpg key?
In which version should I try (Ubuntu, Docker)?
```
Executing: /tmp/tmp.h2LpvBjLSA/gpg.1.sh --keyserver
ha.pool.sks-keyservers.net
--recv-keys
5072E1F5
gpg: requesting key 5072E1F5 from hkp server ha.pool.sks-keyservers.net
?: ha.pool.sks-keyservers.net: Cannot assign requested address
gpgkeys: HTTP fetch error 7: couldn't connect: Cannot assign requested address
gpg: no valid OpenPGP data found.
gpg: Total number processed: 0
gpg: keyserver communications error: keyserver unreachable
gpg: keyserver communications error: public key not found
gpg: keyserver receive failed: public key not found
```

**Comment by GyunerZeki** [comment]
Hi @erajuan 

can you try to install using the new way?

```
docker run -itd -p=110:110 -p=25:25 -p=995:995 -p=80:80 -p=443:443 -p=587:587 -p=993:993 -p=143:143 -p=465:465 -h "YOUR_DOMAIN_NAME" --name="" easymail/easymail:v1.0.3 /bin/sh -c "bash /opt/easymail/post_install.sh YOUR_DOMAIN_NAME; exec /bin/bash"
```
Do you still have the problem with it?

That should install less than a minute without any problems. 
Please let me know if you face any issue.

Thanks, 
Gyuner Zeki

**Comment by erajuan** [comment]
it is run, and  try v1.0.7 too it is ok the installation
