### ISSUE TITLE
Management API Installation failed

### ISSUE THREAD

**Issue by Kiewiet1024** [runeasymail/easymail#176]
Hi,

I had an issue with the management API not installing, being that in the ManagementAPI/install.sh there is a variable $MANAGEMENT_API_VERSION set to 0.2-RC1 like in this link  https://github.com/runeasymail/ManagementAPI/releases/download/0.2-RC1/ManagementAPI
As soon as I set it to an available version it worked no problem.

Loving easymail
Kiewiet1024

**Comment by GyunerZeki** [comment]
Hi @Kiewiet1024 

In the new version of EasyMail, the ManagementAPI is coming already installed in  EasyMail.
Which version of EasyMail are you facing this problem?

Thanks,
Gyuner Zeki

**Comment by GyunerZeki** [comment]
No update from @Kiewiet1024 closing the ticket. Please re-open if you still think it's still relevant
