### ISSUE TITLE
Roundcube doesn't work on Ubuntu 16.04.1 x64

### ISSUE THREAD

**Issue by GyunerZeki** [runeasymail/easymail#18]
The is happening because https://github.com/runeasymail/easymail/blob/master/roundcube/install.sh#L5  and especially the package php5-fpm doesn't exist anymore in Ubuntu 16.04

**Comment by pavel-tashev** [comment]
https://github.com/runeasymail/easymail/commit/7af7d17d07b865cb1e81847596b63b1685039194
https://github.com/runeasymail/easymail/commit/b2438c91e77062250f3146b77aeb782180bd3620
https://github.com/runeasymail/easymail/commit/03f6d0d27a1dc9ee6c8f10a79ddefcf346c97d3c
https://github.com/runeasymail/easymail/commit/d7154935df25e00996a97cdfa15c06affa8d6e54
