### ISSUE TITLE
Volume mounts for storing data?

### ISSUE THREAD

**Issue by cruisemaniac** [runeasymail/easymail#210]
Why doesnt the docker command mount any volumes that ensure that data is persisted across boots? Am I missing a very important picture here???

**Comment by GyunerZeki** [comment]
If you use the suggested way. It mounts.
The suggested way is:
```
export E="yourdomain.com" && wget -qO- https://www.runeasymail.com/get | sh
```

**Comment by cruisemaniac** [comment]
This is a valid point! Closing bug!
