### ISSUE TITLE
Enhancement Roadmap

### ISSUE THREAD

**Issue by cruisemaniac** [runeasymail/easymail#212]
Hey guys,

I wish to propose the following enhancements and perhaps my reasoning at why I'd want easymail configured / setup this way:

1. Support for Nginx on host - The current setup has nginx inside the docker container running ports 80 and 443. Many folks, me included would like the nginx server to be handled by the host - This lets the user run other applications. We could probably run nginx inside the containers as an upstream on non-standard ports and have the host's nginx install proxy things into the container. This brings us to another annoyance - SSL on the upstream is no longer required!

2. Usage of existing Letsencrypt certificates - One of the customers I work with already has certificates installed via letsencrypt using point-1 above. This said, easymail creating another set of certs is both unnecessary and confusing. At the moment, the autorun setup does not have a way to toggle this or control this even.

3. While this is a self contained install, I'm forced to run 2 mysql server instances again related to point 1.

4. The Management API if exposed as a CLI interface would be a kicker!

Looking forward to hearing your thoughts! I'm posting here since the slack channel seems to be way too silent these days ;-)

**Comment by cruisemaniac** [comment]
And most importantly, the README's and the installation instructions need to be updated. The latest image is `v1.0.28` while the installation instructions read `v1.0.7` which isnt on docker even.

**Comment by GyunerZeki** [comment]
Hi @cruisemaniac 

I am definitely for all this functionally/changes, but we have no plans to do it in near future. I would be happy for PR.

Thanks,
Gyuner Zeki
