### ISSUE TITLE
Can the Dockerfile be made public please?

### ISSUE THREAD

**Issue by cruisemaniac** [runeasymail/easymail#213]

**Comment by GyunerZeki** [comment]
The full easymail code base is public, there is no Dockerfile. Please have a look at https://github.com/runeasymail/easymail/blob/master/.travis.yml

**Comment by cruisemaniac** [comment]
Is that all that we're using to build? The quirk here is that we do not have repeatable builds - no base images to build off of except for `ubuntu:16.04`.

**Comment by GyunerZeki** [comment]
Technically is bash script in same it would be in DockerFile. So this doesn't really change the repeatable builds. Said that, yes we're based on `ubuntu:16.04` image. If you want you can provide PR for it.
