### ISSUE TITLE
Renew Lets Encrypt Certificates

### ISSUE THREAD

**Issue by Kiewiet1024** [runeasymail/easymail#214]
How can the lets encrypt certificates be renewed? For web and mail purposes.
Any help will highly be appreciated

**Comment by GyunerZeki** [comment]
Hi @Kiewiet1024 thank you so much for contacting us. @yuksbg we have a method in the ManagmentAPI for the set up of lets encrypt certificates, but I think we have a plan to implement it very soon, am I wrong?

**Comment by Kiewiet1024** [comment]
Hi @GyunerZeki , I did try the generate letsencrypt certificate from the api, but was unsuccessful. Here is what I did:
command: curl -kX POST  -F "username=myusername" -F "password=mypassword" "https://mailx.domain.com/api/auth"
response: Token was generated
command: curl -kX POST -H "Auth-token: generatedToken" -H "Cache-Control: no-cache" -F "hostname=domain.com" "https://mailx.domain.com/api/ssl/letsencrypt/install"
response: {"error":"Let's encrypt error","result":false}

I am not sure if this could be used to renew the certificates, and is there another way around to renew the certificates

Thanks

**Comment by GyunerZeki** [comment]
Hi, @Kiewiet1024 even if its error did you try if it actually works after that?

**Comment by Kiewiet1024** [comment]
Hi @GyunerZeki , I still get the error afterwards: 
SSL_accept error from static.XXX.XXX.XX.XX.clients.your-server.de[XX.XX.XXX.XXX]: 0
warning: TLS library problem: error:14094415:SSL routines:ssl3_read_bytes:sslv3 alert certificate expired:s3_pkt.c:1487:SSL alert number 45:

Thanks

**Comment by GyunerZeki** [comment]
Hi, @Kiewiet1024  I was able to reproduce the problem. We will fix that soon and update the ticket. Thanks

**Comment by Kiewiet1024** [comment]
@GyunerZeki , much appreciated

**Comment by Kiewiet1024** [comment]
@GyunerZeki , was just wondering if this is fixed and updated yet. Thanks

**Comment by GyunerZeki** [comment]
@Kiewiet1024 still not updated, but I have a solution, can you contact me at me[ at ]gzeki.com and I will be happy to share the solution thanks.
