### ISSUE TITLE
EasyMail not accepted when doing right mouse button ”Send to”->Mail recipient

### ISSUE THREAD

**Issue by MagnusBjelksjo** [runeasymail/easymail#215]
EasyMail not accepted when doing right mouse button ”Send to”->Mail recipient. Win 10 just sak no email Client is installed.

**Comment by GyunerZeki** [comment]
Hello @MagnusBjelksjo not sure that I got your questions 100%,  but Easymail is not an email clinet, Easymail is server which means you still need to have email clinet if you want to use the "send to".

If course you can use the web version too, but you will not have "Send to" there at all.

Please elaborate a bit the question so I can try to explain better :)
