### ISSUE TITLE
Web site https://www.runeasymail.com/ down

### ISSUE THREAD

**Issue by jgdubuis** [runeasymail/easymail#217]
Hello,
Sorry to say that, but you did not renew your GoDaddy domain hosting.
"NOTICE: This domain name expired on 10/16/2018 and is pending renewal or deletion."

Would like to make something ?
Thank you ,
Jean

**Comment by GyunerZeki** [comment]
Hello @jgdubuis 

Yes, I know there is a new domain. I have just set it up. 
http://easy.supersecure.email

If you still experience an issue with that, please ping me. Closing this ticket  :) 

Thanks,
Gyuner
