### ISSUE TITLE
How to use the API?

### ISSUE THREAD

**Issue by Nedimko123** [runeasymail/easymail#221]
Hello, good sir.

I am trying to use the API to add DKIM records to see if that helps my mails not getting marked as spam, but I cannot get API to work as there is no documentation on how to start using it.

https://github.com/runeasymail/ManagementAPI - I have installed Go and tested it, works. But, I can't get this API installed. I have git cloned your ManagementAPI and this happens when I try to run it:

`root@postfix:~/ManagementAPI# go build -o main.go 
main.go:4:2: cannot find package "github.com/gin-gonic/gin" in any of:
	/usr/local/go/src/github.com/gin-gonic/gin (from $GOROOT)
	/root/go/src/github.com/gin-gonic/gin (from $GOPATH)
main.go:5:2: cannot find package "github.com/op/go-logging" in any of:
	/usr/local/go/src/github.com/op/go-logging (from $GOROOT)
	/root/go/src/github.com/op/go-logging (from $GOPATH)
main.go:6:2: cannot find package "github.com/runeasymail/ManagementAPI/helpers" in any of:
	/usr/local/go/src/github.com/runeasymail/ManagementAPI/helpers (from $GOROOT)
	/root/go/src/github.com/runeasymail/ManagementAPI/helpers (from $GOPATH)
main.go:7:2: cannot find package "github.com/runeasymail/ManagementAPI/middlewares" in any of:
	/usr/local/go/src/github.com/runeasymail/ManagementAPI/middlewares (from $GOROOT)
	/root/go/src/github.com/runeasymail/ManagementAPI/middlewares (from $GOPATH)
main.go:8:2: cannot find package "github.com/runeasymail/ManagementAPI/modules" in any of:
	/usr/local/go/src/github.com/runeasymail/ManagementAPI/modules (from $GOROOT)
	/root/go/src/github.com/runeasymail/ManagementAPI/modules (from $GOPATH)
root@postfix:~/ManagementAPI# go build -o main
main.go:4:2: cannot find package "github.com/gin-gonic/gin" in any of:
	/usr/local/go/src/github.com/gin-gonic/gin (from $GOROOT)
	/root/go/src/github.com/gin-gonic/gin (from $GOPATH)
main.go:5:2: cannot find package "github.com/op/go-logging" in any of:
	/usr/local/go/src/github.com/op/go-logging (from $GOROOT)
	/root/go/src/github.com/op/go-logging (from $GOPATH)
main.go:6:2: cannot find package "github.com/runeasymail/ManagementAPI/helpers" in any of:
	/usr/local/go/src/github.com/runeasymail/ManagementAPI/helpers (from $GOROOT)
	/root/go/src/github.com/runeasymail/ManagementAPI/helpers (from $GOPATH)
main.go:7:2: cannot find package "github.com/runeasymail/ManagementAPI/middlewares" in any of:
	/usr/local/go/src/github.com/runeasymail/ManagementAPI/middlewares (from $GOROOT)
	/root/go/src/github.com/runeasymail/ManagementAPI/middlewares (from $GOPATH)
main.go:8:2: cannot find package "github.com/runeasymail/ManagementAPI/modules" in any of:
	/usr/local/go/src/github.com/runeasymail/ManagementAPI/modules (from $GOROOT)
	/root/go/src/github.com/runeasymail/ManagementAPI/modules (from $GOPATH)
`

**Comment by GyunerZeki** [comment]
Hello, there is no document, because  the ManagementAPI  is no longer part of Easymail this is why is not coming with Easymail.  The ManagementAPI is deprecated, we recoment using SaaS solution of Easymail. [SuperSecure.Email ](https://www.supersecure.email/)
