### ISSUE TITLE
Incoming email encryption

### ISSUE THREAD

**Issue by alexanderadam** [runeasymail/easymail#222]
Hi folks,

I just stumbled over EasyMail and I was wondering if EasyMail has support for encrypting incoming emails.

For instance [a little implementation of Pretty Easy privacy (p≡p) like described in this blog post](https://blog.jak-linux.org/2019/06/13/encrypted-email-storage/) or at least [MailCrypt support](https://doc.dovecot.org/configuration_manual/mail_crypt_plugin/#mail-crypt-plugin) ([here's a description how to integrate](https://blog.onefellow.com/post/167267172603/server-side-email-encryption-with-dovecot)).

[p≡p](https://www.pep.security/) would surely be the best and most modern variant.

**Comment by GyunerZeki** [comment]
Hello @alexanderadam it sounds like a good idea, unfortunately the project is frozen. There are not active contributes, if there is Pull requests I will review it, but other I don't see any other contributes right now.

**Comment by alexanderadam** [comment]
Thank you for responding. I wasn't aware that the project is frozen.

So maybe you might want to write that in the README and/or use the archiving functionality of GitHub?

**Comment by GyunerZeki** [comment]
@alexanderadam it's not a bad idea. The only reason I haven't done that is because the product is used in production environments and if someone find a security issue I will still fix it dissipate that there are no other contributors.

**Comment by alexanderadam** [comment]
You can write that in the readme exactly like this :wink: 


Or you could advice recommending migrating to 

* https://github.com/mailcow/mailcow-dockerized
* https://github.com/Mailu/Mailu
* https://github.com/tomav/docker-mailserver
* https://github.com/modoboa/modoboa/
* https://github.com/cpt-lamar/mailbooze
* https://github.com/zokradonh/kopano-docker
* https://poste.io/doc/getting-started#download

and/or others

**EDIT**: I closed the issues now, because of the [frozen state](https://github.com/runeasymail/easymail/issues/222#issuecomment-665711411)
