### ISSUE TITLE
Add letsencrypt 

### ISSUE THREAD

**Issue by GyunerZeki** [runeasymail/easymail#24]
In case customer doesn't have own SSL certificate we can provide free SSL certificate via letsencrypt.

More information at https://letsencrypt.org/getting-started/

**Comment by coenier** [comment]
Would be a great feature to add.

**Comment by GyunerZeki** [comment]
Hi @coenier thank you so much for showing interest. This help us to prioritise what to do first. Soon we are going to support letsencrypt.

**Comment by MuhPirat** [comment]
Same as at the API, did you start? If not, I would add this :-)

//Mumu

**Comment by GyunerZeki** [comment]
Hi @MuhPirat 

Yes, I started it, but I haven't finished it yet.

Do you want to join in our Slack channel where we can discuss and share what we have done and what you think is a good idea to be done?

Thanks,
Gyuner

**Comment by yuksbg** [comment]
It's done and merged in Master branch

https://github.com/runeasymail/easymail/pull/78/
