### ISSUE TITLE
Create initial rest API which will be accessible after successful installation.

### ISSUE THREAD

**Issue by GyunerZeki** [runeasymail/easymail#54]

**Comment by MuhPirat** [comment]
Hey,
Do you have an initial code for this? Want to help a little bit.

//Muhpirat

**Comment by GyunerZeki** [comment]
Hi @MuhPirat 

As a start, I want to say welcome ;)

We don't have initial code for that, but we were thinking to use https://github.com/APIJet/APIJet as a PHP framework for the API, but if you have something in mind please share it.

We are open for all kind of solutions. Do you want to start it?

Thanks,
Gyuner

**Comment by MuhPirat** [comment]
Hey @GyunerZeki Thank you for the fast answer. Sure. muhpirat@alenan.org, please add me. ;-)


Thanks,
Mumu

**Comment by GyunerZeki** [comment]
Hi @MuhPirat 

You should have an invitation now. Please let me know if you don't.

Thanks,
Gyuner
