### ISSUE TITLE
Add demo / screenshots of application to readme and website

### ISSUE THREAD

**Issue by iamchathu** [runeasymail/easymail#64]
Add screenshots of application or a demo site to web site so users will interest to try.

**Comment by GyunerZeki** [comment]
Hi @iamchathu 

Welcome and thank you so much for showing an interest of Easymail.

Yes, I totally agree with you, we should put some screenshots.  Do you have something specific in mind?

Thanks,
Gyuner

**Comment by GyunerZeki** [comment]
Missing specific details. Closing this ticket. Please re-open in case it still relevant and there are specific details
